"""add bookings and call_logs

Revision ID: 824b2e9643aa
Revises: ebc349384d1e
Create Date: 2026-06-29 16:50:32.157741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogenerated migrations
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '824b2e9643aa'
down_revision: Union[str, Sequence[str], None] = 'ebc349384d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('property_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cal_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('attendee_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attendee_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_cal_uid'), 'bookings', ['cal_uid'], unique=False)
    op.create_index(op.f('ix_bookings_idempotency_key'), 'bookings', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_bookings_phone'), 'bookings', ['phone'], unique=False)
    op.create_index(op.f('ix_bookings_room_name'), 'bookings', ['room_name'], unique=False)
    op.create_index(op.f('ix_bookings_uuid'), 'bookings', ['uuid'], unique=True)
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('room_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('buyer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_buyer_phone'), 'call_logs', ['buyer_phone'], unique=False)
    op.create_index(op.f('ix_call_logs_room_name'), 'call_logs', ['room_name'], unique=False)
    op.create_index(op.f('ix_call_logs_uuid'), 'call_logs', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_uuid'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_room_name'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_buyer_phone'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_bookings_uuid'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_name'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_phone'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_idempotency_key'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_cal_uid'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
